# Generated by Django 5.1 on 2024-08-27 07:43

import localflavor.in_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='DL', max_length=2),
        ),
    ]
